name: copywriter
description: Checks for copyright headers in each file.
version: 1.1.0
repository: https://github.com/johnpryan/copywriter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.1.0
  mustache_template: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
executables:
  copywriter: copywriter
